linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag

    # Deprecated ones:
    - execinquery
    - gomnd
    - exportloopref

linters-settings:
  gocyclo:
    min-complexity: 15
