name: Go
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.16

      - uses: actions/checkout@v3

      - run: go run .
